version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    groups:
      minor-dependencies:
        patterns: ["*"]
        update-types:
          - minor
          - patch
      major-dependencies:
        patterns: ["*"]
        update-types:
          - major
