version: 1

release:
  name_template: "pro v{{.Version}}"

# https://goreleaser.com/customization/archive/
archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    goos: [windows]
    goarch: [386, amd64]
  - id: linux
    goos: [linux]
    goarch: [amd64, arm64]
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]

brews:
  - repository:
      owner: wowu
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_REPO_TOKEN }}"
    homepage: https://github.com/wowu/pro
    license: MIT

nfpms:
  - id: packages
    maintainer: wowu
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    license: MIT
    homepage: https://github.com/wowu/pro
    description: A single command to quickly open current PR in browser.
    formats:
      - deb
      - rpm

scoops:
  - repository:
      owner: wowu
      name: scoop
      token: "{{ .Env.GORELEASER_REPO_TOKEN }}"
    description: A single command to quickly open current PR in browser.
    license: MIT

publishers:
  - name: fury.io
    ids: [packages]
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/wowu/

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
      - "^chore:"
      - "^refactor:"
      - "^test:"
      - "^build:"
