before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    goos: [windows]
    goarch: [386, amd64]
  - id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]
