release:
  name_template: "pro v{{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    goos: [windows]
    goarch: [386, amd64]
  - id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]

brews:
  - tap:
      owner: wowu
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_REPO_TOKEN }}"
    homepage: https://github.com/wowu/pro
    license: MIT

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - '^test:'
